#!/usr/bin/env bash
# This is a Bash script that displays lines containing the bash word, thereby allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
list=$(ps -afux | grep bash)
echo "$list"
