#!/usr/bin/env bash
# This is a Bash script that displays "To infinity and beyond" continously.
printsig () {
    echo "I am invincible!!!"
    trap - SIGTERM
}

while :
do
    trap printsig SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
