#!/usr/bin/env bash
# This is a script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.
j=0
while [ $j -lt 10 ]
do
    if [ $j == 9 ]
    then
        echo 'Hi'
    fi

    echo 'Best School'
    ((j++))
done
