#!/usr/bin/env bash
# A code for a script that loops from 1 to 10 and:
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Best School" for the other iterations
j=0
while [ $j -lt 10 ]
do
    if [ $j == 3 ]
    then
        echo 'bad luck'
    elif [ $j == 7 ]
    then
        echo 'good luck'
    else
        echo 'Best School'
    fi
    ((j++))
done
