#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# to display hours from 0 to 12
# to display minutes from 1 to 59
hour=0
while [ $hour -le 12 ]
do
    printf "Hour: %d\n" $hour
    minutes=1
    while [ $minutes -le 59 ]
    do
        printf "%d\n" $minutes
        ((minutes++))
    done
    ((hour++))
done
