#!/usr/bin/env bash
# This is a Bash script that configures a server (linux, unix etc) with the below requirements.
# The Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts /etc/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.new
sed -i '2i8.8.8.8 facebook.com' /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
